# Generated by Django 4.0 on 2022-01-12 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('payment_date', models.DateTimeField()),
                ('mode_of_payment', models.CharField(default='cash', max_length=50)),
                ('comments', models.TextField(blank=True, default='', max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', related_query_name='payment', to='order.order')),
            ],
            options={
                'db_table': 't_payment',
                'ordering': ('-payment_date',),
            },
        ),
    ]
