# Generated by Django 4.0 on 2022-01-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ('-created_on',), 'verbose_name_plural': 'businesses'},
        ),
    ]
