# Generated by Django 4.0 on 2022-01-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_business_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
