# Generated by Django 4.0 on 2022-03-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_userprofile_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(default='single', max_length=32),
        ),
    ]
