# Generated by Django 4.0 on 2022-04-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_userbusinessrelation_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbusinessrelation',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
