# Generated by Django 4.0 on 2022-01-11 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_alter_business_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('discount', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('delivery_date', models.DateTimeField()),
                ('order_status', models.CharField(default='Not yet started', max_length=64)),
                ('comments', models.TextField(blank=True, default='', max_length=1024)),
                ('is_one_time_delivery', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.user')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('item_type', models.CharField(max_length=255)),
                ('item_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(default='Not yet started', max_length=64)),
                ('delivery_date', models.DateTimeField()),
                ('comments', models.TextField(blank=True, default='', max_length=512)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', related_query_name='order_item', to='order.order')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
