# Generated by Django 4.0 on 2022-01-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='t_order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='t_order_item',
        ),
    ]
